server:
  serverId: 100
  db:
    sdp:
        connectionLimit: 1
        host: http://localhost:3000
        password: YOUR_PASSWORD
        port: 3306
        username: replicate
  kinesis:
    region: eu-west-1
    accessKeyId: YOUR_KEY_ID
    secretAccessKey: YOUR_ACCESS_KEY
    sdp:
        tables: ['table_1']
        mapping:
            table_1: stream_1
        size:
            table_!: 500

